# BEGIN_KITTY_THEME
# Nord
include current-theme.conf
# END_KITTY_THEME

font_size 14.0

font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic

tab_bar_edge top
tab_bar_style powerline
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{tab.active_oldest_wd}/ {sup.index}"

map ctrl+shift+t new_tab_with_cwd !neighbor

resize_in_steps yes

shell_integration enabled

enable_audio_bell no
